doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'App\Framework\Migrations': '%kernel.project_dir%/src/Framework/Migrations'
    enable_profiler: false
