version: '3.8'

services:
  php:
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "57174:57174"

  nginx:
    ports:
      - "8088:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d

  db:
    environment:
      MYSQL_DATABASE: symfony_dev
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data_dev:/var/lib/mysql
    ports:
      - "3308:3306"
    platform: linux/x86_64

volumes:
  db_data_dev:
