name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1.10'

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Code check (CS-Fixer)
        run: php vendor/bin/php-cs-fixer check

      - name: Archive dependencies
        run: tar -czf dependencies.tar.gz vendor
      - name: Upload dependencies
        uses: actions/upload-artifact@v2
        with:
          name: dependencies
          path: dependencies.tar.gz

  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1.10'

      - name: Download dependencies
        uses: actions/download-artifact@v2
        with:
          name: dependencies
          path: .

      - name: Extract dependencies
        run: tar -xzf dependencies.tar.gz

      - name: Run Architecture tests
        run: make test-architecture

      - name: Run Unit tests
        run: make test-unit

      - name: Run Behat tests
        run: make test-behat
