name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl, xdebug
          ini-values: |
            memory_limit=2G
          coverage: xdebug

      - name: Install Composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          php -r "unlink('composer-setup.php');"

      - name: Pre CI Setup Outside Container
        run: make pre-ci-setup

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Wait for services to be ready
        run: sleep 15

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run migrations
        run: docker-compose exec -T php make migrate

      - name: CS Fixer
        run: docker-compose exec -T php php vendor/bin/php-cs-fixer fix --using-cache=no

      - name: Architecture tests
        run: docker-compose exec -T php make test-architecture

      - name: Unit tests
        run: docker-compose exec -T php make test-unit

      - name: Behat tests
        run: docker-compose exec -T php make test-behat

      - name: Tear down Docker Compose
        run: docker-compose down
